### ISSUE TITLE
Node is placed out of the screen boundaries

### ISSUE THREAD

**Issue by anhduc130** [wynnset/tapestry-wp#121]
Steps to reproduce:
- Create the 1st node
- Create the 2nd node

Result:
- The 1st node is now moved out of the screen boundaries

**Comment by narendrasss** [comment]
I'm going to start taking a look at this.

**Comment by anhduc130** [comment]
I think this will be fixed due to the fix in PR #130.

**Comment by wynnset** [comment]
Fixed via #130
