### ISSUE TITLE
The root node is very large after being created

### ISSUE THREAD

**Issue by anhduc130** [wynnset/tapestry-wp#122]
Steps to reproduce:
- Create an empty tapestry
- Add root node

Result:
- The root node is very large and almost covers the entire screen

Workaround:
- Refresh the page

**Comment by wynnset** [comment]
I think this is also related to issue #126 . Basically, what we want to do is to limit how big the nodes get in general and take that into account when we update the Svg dimensions. Preferably, the nodes would be horizontally centered on the page (or vertically centered on mobile) in such a case, but that might get complicated.

**Comment by wynnset** [comment]
Fixed via #131
