### ISSUE TITLE
Improve auto-scaling UX

### ISSUE THREAD

**Issue by wynnset** [wynnset/tapestry-wp#126]
We need to do 2 things:
1. Set a limit for how big we want the nodes to get and not allow auto-scaling to grow the tapestry beyond that point.
2. When a node is clicked on, automatically scroll the page up or down so that node is clearly visible (and centred as much as possible) 

Based out of these conversations with Linnea: https://app.asana.com/0/1126491658233864/1138518553726967/f

**Comment by narendrasss** [comment]
I'll start working on this.
