### ISSUE TITLE
Provide option to author to have embed links open in a new window

### ISSUE THREAD

**Issue by wynnset** [wynnset/tapestry-wp#139]
Currently, when "URL Embed" is selected, the author is prompted to enter a URL and it will be embedded inside the modal when a user opens it. This is good, but we also want to provide the  option to open the URL in a new window instead of in a modal. 

Changes required:
- [ ] Change "URL Embed" Content Type option to say "Link" instead
- [ ] Change "Embed Link" input field label to "URL"
- [ ] Add a radio button with 2 choices: "Open in Tapestry" (selected by default) or "Open in a new Window"
- [ ] If "Open in a new Window" is selected, change the frontend node so it displays a different media icon to indicate the node will open in a new window.
- [ ] If "Open in a new Window" is selected, change the frontend functionality to open the link in a new tab when media icon is clicked on

**Comment by narendrasss** [comment]
Closed via #157
