### ISSUE TITLE
Duplicated Tapestry nodes not displaying correctly

### ISSUE THREAD

**Issue by codygagnon** [wynnset/tapestry-wp#661]
Summary:
Duplicated Tapestry nodes not displaying correctly

Tapestry URL:
https://ubc.tapestry-tool.com/cogs402/tapestry/attention-1/#/

Steps to reproduce:
Duplicate a tapestry, open the duplicated tapestry, select certain nodes (see video attached)

Expected behaviour:
All nodes should display and zoom in/out normally. 

Actual behaviour:
Some nodes are not displaying or zooming in/out normally. 

Environment:
Chrome

Name:
Stephanie

Email address:
steph19980318@gmail.com

Additional information:

———————————————
This task was submitted through Tapestry Bug Report
https://form.asana.com/?hash=1a1dc24c252a4098ca1084aae8d7e83470e44014581c5b9597e071ff6a3e3fa0&id=1145646772307721

Stephanie Chen: This is happening to the original tapestry as well. I re-entered the glitched node's thumbnail link and it displayed correctly right afterwards, but refreshing the page made that node glitch again like shown in the video.

**Comment by yungalyx** [comment]
Closed, tested with current master on Oct 21, 2020. Issue cannot be reproduced.
